version: "2.2"
services:
    util:
      container_name: util
      ports:
        - 3003:3003
      build:
        dockerfile: Dockerfile
        context: .
      volumes:
        - ./src:/util/src
        - /home/raw_mjr:/home/raw_mjr
        - /home/threads.txt:/home/threads.txt
      env_file:
        - ./src/.env